## Introduction to numpy

In [1]:
import numpy as np

## DataTypes & Attributes

In [3]:
# Numpy's main datatype is nd-array
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [20]:
a2 = np.array([
    [1,2,3],
    [4,5,6]
])

a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18],
    ]
])


In [21]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
a3.shape

(2, 3, 3)

In [24]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)